name: Accessibility Review
on: [workflow_call, workflow_dispatch]
jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium --with-deps
      - name : Run accessibility tests
        env:
          POSTGRES_SERVICE_URI: ${{secrets.POSTGRES_SERVICE_URI}}
          OPENSEARCH_SERVICE_URI: ${{secrets.OPENSEARCH_SERVICE_URI}}
          OPENSEARCH_PASSWORD: ${{secrets.OPENSEARCH_PASSWORD}}
          OPENSEARCH_USERNAME: ${{secrets.OPENSEARCH_USERNAME}}
          REDIS_SERVICE_URI: ${{secrets.REDIS_SERVICE_URI}}
          INDEX_NAME: ${{secrets.INDEX_NAME}}
          OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: true
          OTEL_RESOURCE_ATTRIBUTES: "service.name=langchain-workshop"


        run: |
          python -m pytest tests --tracing=retain-on-failure
      - name: load artifacts
        if: '!cancelled()'
        uses: actions/upload-artifact@v3
        with:
          name: playwright-results
          path: test-results/
