name: Accessibility Review
on: [workflow_call, workflow_dispatch]
jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium --with-deps
      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sudo -E sh
      - name: Start serving
        run: |
            # Run the background, there is no way to daemonise at the moment
            ollama pull llama3
            
            # A short pause is required before the HTTP port is opened
            ollama serve &
            sleep 5

            # This endpoint blocks until ready
            time curl -i http://localhost:11434
      - name : Run accessibility tests
        env:
          POSTGRES_SERVICE_URI: ${{secrets.POSTGRES_SERVICE_URI}}
          OPENSEARCH_SERVICE_URI: ${{secrets.OPENSEARCH_SERVICE_URI}}
          OPENSEARCH_PASSWORD: ${{secrets.OPENSEARCH_PASSWORD}}
          OPENSEARCH_USERNAME: ${{secrets.OPENSEARCH_USERNAME}}
          REDIS_SERVICE_URI: ${{secrets.REDIS_SERVICE_URI}}
          INDEX_NAME: ${{secrets.INDEX_NAME}}
          OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: true
          OTEL_RESOURCE_ATTRIBUTES: "service.name=langchain-workshop"
        run: |
          python -m pytest tests/accessibility --tracing=retain-on-failure
      - name: load artifacts
        if: '!cancelled()'
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: test-results/
